### PR TITLE
Attempt to fix GridMass (gm still broken)

### PR DESCRIPTION
**Pull request by SteffenHeu**
attempt to fix grid mass (#660)

the created features are weird, i think something is not right with the algorithm since we changed the datamodel.

### CODE REVIEW

**Comment by GeertNL** [comment]
Yes, there is definitively something wrong. WHen i look manually it does still seem to isolate mass peaks but subsequent calculations are selected from wrong source i think.

See files:

[Gridmass findings.docx](https://github.com/mzmine/mzmine3/files/8472581/Gridmass.findings.docx)
[export data after gridmassalgo.xlsx](https://github.com/mzmine/mzmine3/files/8472583/export.data.after.gridmassalgo.xlsx)

**Comment by robinschmid** [comment]
This is the direct link to all downloads that should appear at the bottom of the page:
https://github.com/mzmine/mzmine3/actions/runs/2156209683

**Comment by SteffenHeu** [comment]
Hey @GeertNL, did you have the opportunity to test it?

**Comment by GeertNL** [comment]
I tested it and the area difference seems to be consistantly 60 times lower in mzMine3.
I pulled 5 random peaks and compared them.
[MZmine 2.53 vs MZmine 3 gridmass Area.xlsx](https://github.com/mzmine/mzmine3/files/8638931/MZmine.2.53.vs.MZmine.3.gridmass.Area.xlsx)

**Comment by SteffenHeu** [comment]
Thanks for the reply, @GeertNL. We will merge the PR then, since the difference of 60 is expected and will not be fixed. (see https://github.com/mzmine/mzmine3/issues/621)

**Review by robinschmid — APPROVED** [review]
Looks good to me

**Pull request merged**
