### PR TITLE
increased control contrast, styled tree view

### PR DESCRIPTION
**Pull request by SteffenHeu**
TreeView style matches ListView
Background of Tree-, List-, TreeTable-, TableView use the odd cell background colour instead of the button bg colour, so doesnt suddenly change once a file/flist is loaded.
Increased contrast on buttons/controls in general.
grafik

### CODE REVIEW

**Comment by SteffenHeu** [comment]
EDIT: What do you think about this:
grafik
Light

grafik
Dark

**Comment by robinschmid** [comment]
looks great.
Can you make the headers smaller? Would be nice to safe a little space with the height of the tabs

**Comment by SteffenHeu** [comment]
grafik
Like this? I also dont want it to look bunched

**Comment by robinschmid** [comment]
Yeah

**Pull request merged**
