### PR TITLE
Sort formulas module

### PR DESCRIPTION
**Pull request by robinschmid**
A new module to sort predicted formulas.
This module is also used within the FeatureListFormulaPrediction 

The scoring could be improved. So far it uses 
(maxPPM-actualPPM)/maxPPM + msmsScore*msmsFactor + isotopeScore*isotopeFactor

image

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
@robinschmid Could you please setup your Eclipse to use the `mzmine-eclipse-code-formater.xml` for formatting the sources, and then reformat your whole tree like this?

Screen Shot 2019-12-15 at 15 09 08

That way we can avoid having so many whitespace changes in the pull requests.

**Comment by tomas-pluskal** [comment]
I think this looks good, so let's merge it.

**Comment by kkcau9118** [comment]
> I think this looks good, so let's merge it.

Hi Tomas,

I tried to Merge the new module (sorting predicted formulas, which was contributed by Robin) to my MZmine3 by right-click 'Team', click 'Merge', select 'Remote Tracking' (please see the screenshots). However, it seems that the Merging is not successful.  Or Do I need to clone the newest MZmine3 (which includes the new module for sorting predicted formulas) in my Eclipse IDE? Thanks!
image
image

Best,

Kai

**Comment by robinschmid** [comment]
This should usually be in a new issue.
The correct way would be to add the mzmine3 repository to your remotes and then fetch all branches from there. 
Then you can create a new branch or merge the latest changes into your branch.

We are currently changing a lot in the main structure of the code - this might break a few things. You could also try to get my branch.

Or you could create a pull request of my branch to your main branch

image

**Pull request merged**
