### PR TITLE
MZmine 3 introduction tab

### PR DESCRIPTION
**Pull request by roman-bushuiev**
Working on the new implicitly opened tab when opening MZmine.

### CODE REVIEW

**Comment by robinschmid** [comment]
Maybe you can show it to me later. 
Do you want to merge it before the workshop?

**Comment by tomas-pluskal** [comment]
I would like to merge this before the workshop.

**Comment by roman-bushuiev** [comment]
> Maybe you can show it to me later.
> Do you want to merge it before the workshop?

Sure, I'll add a screenshot to the PR, but it is raw atm.

**Comment by roman-bushuiev** [comment]
image

**Pull request merged**
