### PR TITLE
windows uknown folder issue

### PR DESCRIPTION
**Pull request by knakul853**

### CODE REVIEW

**Comment by knakul853** [comment]
It worked in my windows please let me know if it works on your system as well

**Comment by tomas-pluskal** [comment]
Looks good, but please change "MZmine Software" to just "MZmine". Thanks!

**Comment by tomas-pluskal** [comment]
A few more things to add:

- the "--license-file" parameter so the user has to accept the MZmine license (see https://docs.oracle.com/en/java/javase/14/jpackage/manage-installation.html#GUID-55A24EF7-A3C4-48B3-B157-13248826BAA4)
- the "--linux-..." parameters to configure the installation, similar to the Windows ones. For example "--linux-shortcut", "--linux-menu-group", etc. Check all relevant Linux-specific options here: https://openjdk.java.net/jeps/343
- make sure the linux installer shows the MZmine icon
- you can add my email address (plusik@gmail.com) to "--linux-deb-maintainer"

**Comment by knakul853** [comment]
Hey checked only on Linux and worked fine. The license moved to the resources as it seems standard place.let me know if it worked on another os

**Comment by tomas-pluskal** [comment]
Great, but please keep the license in the root folder - it is a convention on GitHub that each project should have the license file in the root folder.

**Comment by knakul853** [comment]
Okk

**Pull request merged**
