### PR TITLE
DeconvolutionUtils

### PR DESCRIPTION
**Pull request by SteffenHeu**
General Adaption of the LocalMinimumDeconvolution module to deconvolve any kind of xy-data.

The current Method also takes a set of indices, which can be equivalient to the scan numbers.
Both, indices and y data need to be **strictly monotonically increasing**. Note that this is not the case for TIMS data which caused me some pain to wrap my head around. This is also the case why i call it indices and not scan numbers. The other reason for that parameter to exist is, because you could perform deconvolution on smoothed data, but build the deconvolved data from the raw data by using the indices.

Edit: now there is also a method that does not rely on the indices as they might be useless for most applications.

### CODE REVIEW

**Comment by SteffenHeu** [comment]
@Annexhc can you work with this in your IonMobilityTraces?

**Comment by Annexhc** [comment]
Great! I think so, but I have to do some testing :-)

**Comment by SteffenHeu** [comment]
For some reason the removed MSnFeauteListBuilder module is not updated properly in this branch. Merging this again with the current master does not seem to work. Any suggestions?
https://github.com/SteffenHeu/mzmine3/blob/0279304b6a61ad55d705f52d20789be3da30ff49/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_msn/MsnPeakPickingTask.java#L202

**Comment by tomas-pluskal** [comment]
> For some reason the removed MSnFeauteListBuilder module is not updated properly in this branch. Merging this again with the current master does not seem to work. Any suggestions?
> https://github.com/SteffenHeu/mzmine3/blob/0279304b6a61ad55d705f52d20789be3da30ff49/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_msn/MsnPeakPickingTask.java#L202

The MSnFeatureListBuilder is a new module that was recently merged from Kevin's PR. The PR also removed the older MSMSFeatureListBuilder, but we'll have to update the MSnFeatureListBuilder now because the getFragmentScanNumbers() method was removed.

**Comment by tomas-pluskal** [comment]
I am not sure about this PR. It seems like you are trying to generalize the use of the deconvolution, but at the same time you are not generalizing it (because you are creating a very specific utility method for one specific algorithm).  Wouldn't it make more sense to define a generic interface for deconvolution methods (like `io.github.mzmine.modules.dataprocessing.featdet_chromatogramdeconvolution.PeakResolver` but working with double[] arrays)? The local minimum algorithm can implement this interface. The interface can then be used in chromatogram deconvolution as well as in mobility trace deconvolution.

**Comment by SteffenHeu** [comment]
> 
> 
> > For some reason the removed MSnFeauteListBuilder module is not updated properly in this branch. Merging this again with the current master does not seem to work. Any suggestions?
> > https://github.com/SteffenHeu/mzmine3/blob/0279304b6a61ad55d705f52d20789be3da30ff49/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_msn/MsnPeakPickingTask.java#L202
> 
> The MSnFeatureListBuilder is a new module that was recently merged from Kevin's PR. The PR also removed the older MSMSFeatureListBuilder, but we'll have to update the MSnFeatureListBuilder now because the getFragmentScanNumbers() method was removed.

Damn, i thought it was the other way round.

**Comment by SteffenHeu** [comment]
> 
> 
> I am not sure about this PR. It seems like you are trying to generalize the use of the deconvolution, but at the same time you are not generalizing it (because you are creating a very specific utility method for one specific algorithm). Wouldn't it make more sense to define a generic interface for deconvolution methods (like `io.github.mzmine.modules.dataprocessing.featdet_chromatogramdeconvolution.PeakResolver` but working with double[] arrays)? The local minimum algorithm can implement this interface. The interface can then be used in chromatogram deconvolution as well as in mobility trace deconvolution.

Sounds good.

**Comment by tomas-pluskal** [comment]
Why the double I in IIndexBasedXYResolver?

**Comment by SteffenHeu** [comment]
I for Interface. Probably only worth it if we do it consistently, though.

**Comment by tomas-pluskal** [comment]
Yeah, I think using I for interface is a convention in C#, but not in Java.

**Comment by SteffenHeu** [comment]
Done

**Comment by tomas-pluskal** [comment]
Thanks!

**Pull request merged**
