### PR TITLE
4D IMS ion trace builder

### PR DESCRIPTION
**Pull request by Annexhc**
Added a 4D feature finder for IMS data. Some things are work in progress. I think I have to make some changes after PR#118 from @SteffenHeu. Will make last additions once modular feature list model was adjusted.
image

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
#118 has been merged, it seems there is a single merge conflict in ScanSelection

**Comment by tomas-pluskal** [comment]
By the way the ion mobility trace looks awesome :) 

(minor point: I think we don't use the all-capitals notation in MZmine, e.g., "Ion Mobility Trace" -> "Ion mobility trace")

**Comment by Annexhc** [comment]
thanks Tomas! Will continue working on the PR tomorrow.

**Comment by Annexhc** [comment]
I think we can merge this for now. There are some todos regarding all the feature specific types I will add once the Robin is done, e.g. calculation of quality parameters or area calculation

**Comment by tomas-pluskal** [comment]
Thanks Ansgar!

**Pull request merged**
