### PR TITLE
Java 18

### PR DESCRIPTION
**Pull request by SteffenHeu**
includes #865

### CODE REVIEW

**Comment by SteffenHeu** [comment]
When scrolling through the feature table it jumps to the bottom at some point, making it super annoying. Could not find a fix for that yet.

**Comment by robinschmid** [comment]
I have the same issue and its annoying. Even trying to scroll up it jumps down sometimes. More often for the aligned list.
Maybe its a bug of the new JFX. I was using JDK18 for a while

**Comment by tomas-pluskal** [comment]
Have you guys tried using JavaFX 19 with Java 18? Does it still cause this problem?

**Comment by robinschmid** [comment]
Maybe we should try this

**Pull request closed without merging**
