### PR TITLE
Fix Spectral Deconvolution issue #728

### PR DESCRIPTION
**Pull request by asmirn1**
A fix for the spectral deconvolution/Multivariate Curve Resolution (issue #728)

As a note, I seem my file `src/main/resources/mzmineversion.properties` is different from the master version. I'm pretty sure I didn't change it manually. I guess it's generated automatically?

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
@robinschmid Maybe we should add `src/main/resources/mzmineversion.properties` to `.gitignore`?

**Comment by robinschmid** [comment]
@asmirn1  Is this fix ready?
I guess that many of the comments and TODO entries are from @SteffenHeu

**Comment by asmirn1** [comment]
@robinschmid I've tested it on some data, and the spectral deconvolution/multivariate curve resolution works now. 

Yes, these TODO comments are from @SteffenHeu. We probably need to discuss it with him whether those TODO comments is something that needs to be addressed now and can wait.

I saw the Link Code Base check has failed. Do you want me to fix that? It's mainly lines longer than 80 characters.

**Comment by robinschmid** [comment]
Its an isolated change and seems fine so lets merge and work on it further :)

**Pull request merged**
