### PR TITLE
Annotations & Visualization online help update

### LINKED ISSUE #774: Main window is oversized in Window 10
* operating system: Windows 10
* MZmine version: MZMine 3.1.0-beta

When launched, MZMine main window is too big for a screen and menus are not visible. The issue occurs both for the installed version and built in IntelliJ. The BorderPane parameters in MainWindow.fxml have to be modified.

### PR DESCRIPTION
**Pull request by omokshyna**
Added info on Annotation modules and updated info on Visualization modules (#819).
Additionally fixed problem with main and dialog windows opening with size larger than screen's (closes #774)

### CODE REVIEW

**Comment by SteffenHeu** [comment]
There are some comflicts now

**Comment by omokshyna** [comment]
@SteffenHeu It looks like all the conflicts are the *html help files that should be deleted. Weird as these files shouldn't have been modified by any of the previous merges

**Comment by omokshyna** [comment]
Should be ok now :)

**Comment by SteffenHeu** [comment]
Thanks @omokshyna

**Pull request merged**
