### PR TITLE
fix: ims visualizer layout for small resolutions

### PR DESCRIPTION
**Pull request by arteevraina**
Fixes: #599

### CODE REVIEW

**Comment by arteevraina** [comment]
Hi Steffen . I have made the minimum width of mobilogram to match the minimum width of trace chart.

**Comment by SteffenHeu** [comment]
Basically yes, but the maximum and minimum width of the mobilogram should be limited. i think the maximum can be kept as is, but the minimum should be around 150 pixels or so.

**Comment by arteevraina** [comment]
Screenshot from 2022-03-23 21-15-48

Hi Steffen, just checked the code. We were not setting the maximum width of mobilogram earlier explicitly, we were setting up only minimum width of mobilogram. 

Now, restricted the maximum width of mobilogram to 250 pixels (previous minimum width) and minimum width to 150 pixels.

**Comment by SteffenHeu** [comment]
Hi Arteev, i checked in with the latest changes. The mobilogram is not scaled between the minimum and maximum size when the window is resized. Can you take a look, please?

**Comment by SteffenHeu** [comment]
Closed due to inactivity

**Pull request closed without merging**
