### PR TITLE
Add rpm build on linux

### PR DESCRIPTION
**Pull request by robinschmid**

### CODE REVIEW

**Comment by robinschmid** [comment]
Creates a deb and rpm install file on linux

**Comment by SteffenHeu** [comment]
is this ready?

**Comment by robinschmid** [comment]
Still waiting for feedback from someone

**Comment by robinschmid** [comment]
@SteffenHeu ready

**Comment by SteffenHeu** [comment]
this now fails to release the dev versions -> revert

**Comment by SteffenHeu** [comment]
@robinschmid please open a new pr with a fixed workflow

**Pull request merged**
