### PR TITLE
Fast aligner

### PR DESCRIPTION
**Pull request by SteffenHeu**
Parallelised solution of the join aligner.

All rows are aligned to the full base feature list at once. The alignment happens iteratively.

In each iteration:
- The feature list with the most unaligned rows is chosen as a base list. 
  - the (remaining) features of this feature list are chosen as a base and added to the aligned feature list
- the rows from the new base list are removed from the unaligned rows
- the remaining unaligned rows are aligned to the full aligned feature list (this is done because the row m/z and rt might change after an alignment)
- the rows without an alignmed are used as unaligned rows for the next interation

Realigning on the full feature list is up for debate! Can also just align on the rows of the newly chosen base feature list. What do you think @robinschmid, @tomas-pluskal ?

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
I think we should not have two modules (Join aligner and Parallel Join aligner) that do exactly the same thing, that is confusing for the user. If this new module generates the same results as the old one, we should remove the old one.

**Comment by SteffenHeu** [comment]
I agree. The results are very similar but not exactly the same, however, because the alignment happens for all raw data files in parallel and not consecutively.

**Comment by tomas-pluskal** [comment]
> Should i delete the normal join aligner then?

I think so.

**Comment by SteffenHeu** [comment]
Good?

**Comment by robinschmid** [comment]
The join aligner produces reproducible results when run on the same feature lists in the same sorting....
I guess the fast aligner does not. This is a problem for some people - although I do not know how reproducible we are overall.

**Comment by SteffenHeu** [comment]
Did you try it?
I just ran the aligner 4 times in a row and got the same number of features every time.

grafik

**Comment by SteffenHeu** [comment]
Only the scoring happens in parallel. The actual assignment is sequential.

**Comment by robinschmid** [comment]
I also tested it and it seems to prodcue reproducible results.

**Comment by SteffenHeu** [comment]
Yes i tried that, the total number of rows is different, but not by much.

**Comment by robinschmid** [comment]
This would be fine by me  then

**Pull request merged**
