### PR TITLE
Add major negative ions to IIN refinement 

### PR DESCRIPTION
**Pull request by robinschmid**
@SteffenHeu @Adafede @Annexhc 
There is an optional refinement step in IIN to remove all IIN without major ion. Users can control the creation of IIN initially in the module so this is not super important but still a great hack to reduce the number of weird IIN with little parameter setup. 

I have added some missing negative ions and defined the maximum number of modifications that I would like to allow. For example, M+Na does usually not show abundant in source fragments, M+H does. The list is now:
- M+H (3 max modifications, e.g., M-3H2O+H)
- M+Na (0)
- M+NH4 (1)
- M-H (2)
- M+Cl (0)
- M+formic acid (0)

Any comments, anything to add?

### CODE REVIEW

**Review by SteffenHeu — APPROVED** [review]
looks good to me

**Comment by robinschmid** [comment]
I was using HFA and FA... what would you use?

**Comment by SteffenHeu** [comment]
Sorry i did not see your comment. Hard to say. If the usage is consistent throughout the IIN module its fine i think. Everyone familiar with massspec should know whats going on.

**Comment by Adafede** [comment]
@robinschmid 

Sorry completely missed the tag on that one!

Hmmm....I am actually using n >> 3 modifications, this would imply doing in in n/3 steps, did I get it right?

Btw, could it be related to #575 or not at all?

**Comment by robinschmid** [comment]
Oh this is only about the refinement of IIN. It is completely optional. It is just an option for people to easily filter out all ion identity networks that do not contain one of the main ions. the max 3 modifications for M+H just mean that we do accept that M+H fragments more than M+Na for example.

**Comment by robinschmid** [comment]
#575 will be something else. have to look into this

**Pull request merged**
