### PR TITLE
jdk 16, gradle 7 rc

### PR DESCRIPTION
**Pull request by SteffenHeu**

### CODE REVIEW

**Comment by SteffenHeu** [comment]
I think lgtm doesn't use gradle RCs. So we have to wait until the actual release.

**Comment by robinschmid** [comment]
You are faster than I. 
I also read about the release of gradle 7 and wanted to try it

**Comment by SteffenHeu** [comment]
Oh i just saw the actual gradle 7 version released yesterday. Then it might work now if i adjust the script. Before i was trying to use the release candidate, which didnt work.

**Comment by tomas-pluskal** [comment]
It seems JavaFX now produces a warning when its classes are present on the classpath (instead of the module path, which is the preferred way). See the first issue in the Release Notes: https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-16.md

MZmine is currently not a modular application, but perhaps we should convert it into one. There will be some obstacles on the way.

**Comment by SteffenHeu** [comment]
How high of a priority should it be?

**Comment by tomas-pluskal** [comment]
I have already noticed some issues during the JavaFX Application startup, but it is not something burning.

**Comment by robinschmid** [comment]
Do you mean the jigsaw module system of JDK9? 
As far as I understand - no one uses it :D
Its main advantage is that it modularizes the JDK and you can include only the needed parts of it into your runtime.

**Pull request merged**
