### PR TITLE
Parser for structure IDs (smiles, inchi)

### PR DESCRIPTION
**Pull request by mmattano**
A CDK-based parser to translate SMILES to InChI keys and vice-versa

### CODE REVIEW

**Comment by SteffenHeu** [comment]
Hi mmattano, thank you for contributing. 

I think the test is currently failing.

As far as i can see, the parser currently is not incorporated into any module.
Where do you see implementation of this parser?

In my opinion, this could be incorporated to the parsing process of csv files in the compound database search module, to add additional metadata.

**Comment by mmattano** [comment]
Hi Steffen, thanks for checking! I worked on this with Robin for the BioHackathon and we were planning to use it in an MS2 fragment structure annotation tool

**Comment by SteffenHeu** [comment]
That's great, thanks 👍

**Comment by robinschmid** [comment]
I incorporated this into one of my branches with substructure support. Will create a new PR soon

**Pull request closed without merging**
