### PR TITLE
Add timstof spot dataset test

### PR DESCRIPTION
**Pull request by robinschmid**
Currently failing to import @SteffenHeu can you look into this?

```
Jan 12, 2024 5:22:02 PM io.github.mzmine.modules.io.import_rawdata_bruker_tdf.TDFImportTask readMetadata
INFO: Metadata read successfully for null
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: Precursors)
	at org.sqlite.core.DB.newSQLException(DB.java:1135)
	at org.sqlite.core.DB.newSQLException(DB.java:1146)
	at org.sqlite.core.DB.throwex(DB.java:1106)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:122)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.jdbc3.JDBC3Statement.lambda$executeQuery$1(JDBC3Statement.java:81)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:79)
	at io.github.mzmine.modules.io.import_rawdata_bruker_tdf.datamodel.sql.TDFDataTable.executeQuery(TDFDataTable.java:104)
	at io.github.mzmine.modules.io.import_rawdata_bruker_tdf.TDFImportTask.readMetadata(TDFImportTask.java:386)
	at io.github.mzmine.modules.io.import_rawdata_bruker_tdf.TDFImportTask.run(TDFImportTask.java:236)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:64)
Jan 12, 2024 5:22:02 PM io.github.mzmine.modules.io.import_rawdata_imzml.ImagingParameters <init>
INFO: Number format exception during tdf maldi import.
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: PasefFrameMsMsInfo)
	at org.sqlite.core.DB.newSQLException(DB.java:1135)
	at org.sqlite.core.DB.newSQLException(DB.java:1146)
	at org.sqlite.core.DB.throwex(DB.java:1106)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:122)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.jdbc3.JDBC3Statement.lambda$executeQuery$1(JDBC3Statement.java:81)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:79)
	at io.github.mzmine.modules.io.import_rawdata_bruker_tdf.datamodel.sql.TDFDataTable.executeQuery(TDFDataTable.java:104)
	at io.github.mzmine.modules.io.import_rawdata_bruker_tdf.datamodel.sql.FramePrecursorTable.executeQuery(FramePrecursorTable.java:98)
	at io.github.mzmine.modules.io.import_rawdata_bruker_tdf.TDFImportTask.readMetadata(TDFImportTask.java:389)
	at io.github.mzmine.modules.io.import_rawdata_bruker_tdf.TDFImportTask.run(TDFImportTask.java:236)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:64)
```

### CODE REVIEW

**Comment by SteffenHeu** [comment]
The maldi files do not have the respective tables.

**Comment by SteffenHeu** [comment]
the files import anyway though

**Comment by SteffenHeu** [comment]
Problem is that the expected stats are not loaded correctly: 
grafik

**Comment by robinschmid** [comment]
Tests work and are updated

**Comment by robinschmid** [comment]
timstof test is disabled by default because of constraints of systems

**Pull request merged**
