### PR TITLE
Split charge states in isotope patterns

### PR DESCRIPTION
**Pull request by robinschmid**
So far the isotope finder just throws all isotope signals into the same pattern. Now it uses a MultiChargeStateIsotopePattern and isotope pattern also carry information on the charge state.

relates to PR #519

### CODE REVIEW

**Comment by SteffenHeu** [comment]
Also: No save/load test for MultiChargeIsotopePattern yet

**Comment by SteffenHeu** [comment]
apparently not, so we need one too

**Comment by robinschmid** [comment]
Added tests for simple and multi charge isotope pattern

**Comment by robinschmid** [comment]
@SteffenHeu ready from my side

**Comment by SteffenHeu** [comment]
thanks, robin!

**Pull request merged**
